import React from "react";
import {
    ArrowUp,
    ArrowDown,
    MessageCircle,
    TrendingUp,
    TrendingDown,
    Minus,
} from "lucide-react";

interface SubredditSentimentSummaryProps {
    subredditName: string;
    summary: string;
    positiveSent: number;
    neutralSent: number;
    negativeSent: number;
    postsAnalyed: number;
    keyInsights: string[];
}

const SubredditSentimentSummary: React.FC<SubredditSentimentSummaryProps> = ({
    subredditName,
    summary,
    positiveSent,
    neutralSent,
    negativeSent,
    postsAnalyed,
    keyInsights
}) => {
    return (
        <div
            className="w-full max-w-3xl mx-auto
                       rounded-2xl
                       bg-zinc-900/80 backdrop-blur
                       border border-zinc-800
                       shadow-xl overflow-hidden"
        >
            {/* Header */}
            <div
                className="flex items-center justify-between
                           px-5 py-4 border-b border-zinc-800"
            >
                <div className="flex items-center gap-3">
                    {/* Vote column mimic */}
                    <div className="flex flex-col items-center text-zinc-500">
                        <ArrowUp size={14} />
                        <span className="text-xs font-medium">AI</span>
                        <ArrowDown size={14} />
                    </div>

                    <div>
                        <h2 className="text-sm font-medium text-zinc-100">
                            Reddit - r/{subredditName}
                        </h2>
                        <p className="text-xs text-zinc-500">
                            Sentiment snapshot · last 24h
                        </p>
                    </div>
                </div>

                <span
                    className="text-xs px-3 py-1 rounded-full
                               bg-emerald-600/10 text-emerald-400"
                >
                    Mostly Positive
                </span>
            </div>

            {/* Content */}
            <div className="px-5 py-4 space-y-4 text-sm text-zinc-200">
                <p className="leading-relaxed">
                    The overall mood in{" "}
                    <span className="text-zinc-100 font-medium">
                        r/{subredditName}
                    </span>{" "}
                    {summary}
                </p>

                {/* Sentiment breakdown */}
                <div className="grid grid-cols-3 gap-3 text-xs">
                    <div
                        className="rounded-xl p-3
                                   bg-emerald-600/10 text-emerald-400"
                    >
                        <div className="flex items-center gap-1 mb-1">
                            <TrendingUp size={12} />
                            Positive
                        </div>
                        <p className="text-lg font-semibold">{positiveSent}%</p>
                    </div>

                    <div
                        className="rounded-xl p-3
                                   bg-zinc-800 text-zinc-400"
                    >
                        <div className="flex items-center gap-1 mb-1">
                            <Minus size={12} />
                            Neutral
                        </div>
                        <p className="text-lg font-semibold">{neutralSent}%</p>
                    </div>

                    <div
                        className="rounded-xl p-3
                                   bg-red-600/10 text-red-400"
                    >
                        <div className="flex items-center gap-1 mb-1">
                            <TrendingDown size={12} />
                            Negative
                        </div>
                        <p className="text-lg font-semibold">{negativeSent}%</p>
                    </div>
                </div>

                {/* Insight bullets */}
                <ul className="list-disc list-inside text-zinc-400 space-y-1">
                    {keyInsights?.map((item: string, index: number) => (
                        <li key={index}>{item}</li>
                    ))}
                </ul>
            </div>

            {/* Footer */}
            <div
                className="flex items-center justify-between
                           px-5 py-3 border-t border-zinc-800 text-xs text-zinc-500"
            >
                <div className="flex items-center gap-2">
                    <MessageCircle size={14} />
                    ~{postsAnalyed} posts analyzed
                </div>

                <span>
                    Generated by sentiment engine
                </span>
            </div>
        </div>
    );
};

export default SubredditSentimentSummary;
